import { AppSidebar } from "@/components/sidebar/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { auth } from "@/lib/auth";
import { Metadata } from "next";
import { redirect } from "next/navigation";

type User = {
  id: string
  name: string;
  email: string;
  avatar: string;
  role: string
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function PosLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await auth() as User;

  console.log(user)

  if (user === null) {
    redirect("/");
  }

  return (
    <SidebarProvider>
      <AppSidebar user={user} />
      <main>
        <SidebarTrigger />
        {children}
      </main>
    </SidebarProvider>
  );
}
